<?php
$passHash = password_hash('Onda', PASSWORD_DEFAULT);
echo "Onda - $passHash <br>";
$passHash = password_hash('Cedente', PASSWORD_DEFAULT);
echo "Cedente - $passHash <br>";
$passHash = password_hash('Ganar', PASSWORD_DEFAULT);
echo "Ganar - $passHash <br>";
$passHash = password_hash('Rojo', PASSWORD_DEFAULT);
echo "Rojo - $passHash <br>";
$passHash = password_hash('Picante', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Honorario', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Colosal', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Goldfish', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Esforzarse', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Patrulla', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Relajarse', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Ego', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Pala', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Golfo', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Maduro', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Labio', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Vecino', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Controlar', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Potro', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Agujero', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Blanco', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Flophouse', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Desilusionado', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Compuesto', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Alcanzar', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Horadedormir', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Lubricante', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Pulso', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Polilla', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Vertiginoso', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Proyecto', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Tarde', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Lechoso', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Aguas', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Raster', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Lamentable', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Carisma', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Buffer', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Shock', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Carro', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Oeste', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Grotesco', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Desolador', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Daylight', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Bocado', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Boa', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Sorber', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Agarrar', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Abstinencia', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Planta', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Fiebre', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Concepto', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Sabio', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Ondulante', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Obedecer', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Sombra', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Interrumpir', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Abstinencia', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Planta', PASSWORD_DEFAULT);
echo "$passHash <br>";
$passHash = password_hash('Fiebre', PASSWORD_DEFAULT);
echo "$passHash <br>";

?>